### ISSUE TITLE
設計を見直す

### ISSUE THREAD

**Issue by Godan** [Godan/podcaster-rev#6]
- ドメインモデル図
- ユースケース

**Comment by sinshutu** [comment]
とりあえず、 https://hackmd.io/1yAQfLokQsiNHMYsiw7jhA で下書き

**Comment by sinshutu** [comment]
ユースケース図
https://drive.google.com/file/d/1bYosy-J2Nh6o2VbhY6aID3lSWP6EPuuL/view?usp=sharing

**Comment by sinshutu** [comment]
たたきは作成したので、あとは進めながら設計する
